//
//  TimelineInteractor.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 28/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimelineBusinessLogic
{
  func doSomething(request: Timeline.Something.Request)
}

protocol TimelineDataStore
{
  //var name: String { get set }
}

class TimelineInteractor: TimelineBusinessLogic, TimelineDataStore
{
  var presenter: TimelinePresentationLogic?
  var worker: TimelineWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Timeline.Something.Request)
  {
    worker = TimelineWorker()
    worker?.doSomeWork()
    
    let response = Timeline.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
