//
//  TimelineRouter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 28/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TimelineRoutingLogic
{
  func routeToNewPost(segue: UIStoryboardSegue?)
  func routeToPost(segue: UIStoryboardSegue?)
}

protocol TimelineDataPassing
{
  var dataStore: TimelineDataStore? { get }
}

class TimelineRouter: NSObject, TimelineRoutingLogic, TimelineDataPassing
{
  weak var viewController: TimelineViewController?
  var dataStore: TimelineDataStore?
  
  // MARK: Routing
  
  func routeToNewPost(segue: UIStoryboardSegue?) {
    if let segue = segue {
      //
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "NewPostViewController") as! NewPostViewController
      navigateToNewPost(source: viewController!, destination: destinationVC)
    }
  }
  
  func routeToPost(segue: UIStoryboardSegue?) {
    if let segue = segue {
      let destinationVC = segue.destination as! PostViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPost(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "PostViewController") as! PostViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPost(source: dataStore!, destination: &destinationDS)
      navigateToPost(source: viewController!, destination: destinationVC)
    }
  }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TimelineViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  func navigateToNewPost(source: TimelineViewController, destination: NewPostViewController) {
    // present modal with nav bar & prevent swipe to dismiss & full screen
    let navController = UINavigationController(rootViewController: destination)
    navController.modalPresentationStyle = UIModalPresentationStyle.fullScreen
    source.present(navController, animated: true, completion: nil)
  }
  
  func navigateToPost(source: TimelineViewController, destination: PostViewController) {
    // present modal with nav bar & prevent swipe to dismiss & full screen
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TimelineDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
  
  func passDataToPost(source: TimelineDataStore, destination: inout PostDataStore)
  {
    destination.postAlbum = source.selectedPostAlbum
  }
}
