//
//  TimelinePresenter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 28/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimelinePresentationLogic
{
  func presentNewsFeed(response: Timeline.NewsFeed.Response)
}

class TimelinePresenter: TimelinePresentationLogic
{
  weak var viewController: TimelineDisplayLogic?
  
  // MARK: Do something
  
  func presentNewsFeed(response: Timeline.NewsFeed.Response)
  {
    var posts:[PostAlbum] = []
    response.album.result.forEach { (element) in
      let title = element.title
      
      let responsePhoto = response.albumPhotosDict[element.id]
      var photos:[PostPhoto] = []
      for item in responsePhoto!.result {
        let photo = PostPhoto(title: item.title, url: item.url, thumbnail: item.thumbnail)
        photos.append(photo)
      }
      
      let post = PostAlbum(title: title, photos: photos)
      posts.append(post)
    }
    
    let viewModel = Timeline.NewsFeed.ViewModel(postAlbums: posts)
    viewController?.displayNewsFeed(viewModel: viewModel)
  }
}
