//
//  TimelinePresenter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 28/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimelinePresentationLogic
{
  func presentSomething(response: Timeline.Something.Response)
}

class TimelinePresenter: TimelinePresentationLogic
{
  weak var viewController: TimelineDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Timeline.Something.Response)
  {
    let viewModel = Timeline.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
