//
//  PostInteractor.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 31/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostBusinessLogic
{
  func doSomething(request: Post.Something.Request)
}

protocol PostDataStore
{
  //var name: String { get set }
}

class PostInteractor: PostBusinessLogic, PostDataStore
{
  var presenter: PostPresentationLogic?
  var worker: PostWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Post.Something.Request)
  {
    worker = PostWorker()
    worker?.doSomeWork()
    
    let response = Post.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
