//
//  PostPresenter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 31/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Lightbox

protocol PostPresentationLogic
{
  func presentSelectedPostAlbum(response: Post.SelectedPostAlbum.Response)
  func presentPhotosViewer(response: Post.PhotosViewer.Response)
}

class PostPresenter: PostPresentationLogic
{
  weak var viewController: PostDisplayLogic?
  
  // MARK: Do something
  
  func presentSelectedPostAlbum(response: Post.SelectedPostAlbum.Response)
  {
    let viewModel = Post.SelectedPostAlbum.ViewModel()
    viewController?.displaySelectedPostAlbum(viewModel: viewModel)
  }
  
  func presentPhotosViewer(response: Post.PhotosViewer.Response)
  {
    var images:[LightboxImage] = []
    for photo in response.photos {
      let img: LightboxImage = LightboxImage(imageURL: URL(string: photo.url)!, text: photo.title, videoURL: nil)
      images.append(img)
    }
    
    let viewModel = Post.PhotosViewer.ViewModel(startIndex: response.startIndex, images: images)
    viewController?.displayPhotosViewer(viewModel: viewModel)
  }
}
