//
//  PostInteractor.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 31/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostBusinessLogic
{
  func requestSelectedPostAlbum(request: Post.SelectedPostAlbum.Request)
}

protocol PostDataStore
{
  var postAlbum: PostAlbum { get set }
}

class PostInteractor: PostBusinessLogic, PostDataStore
{
  var presenter: PostPresentationLogic?
  var worker: PostWorker?
  
  var postAlbum: PostAlbum = PostAlbum(title: "", photos: [])
  
  // MARK: Do something
  
  func requestSelectedPostAlbum(request: Post.SelectedPostAlbum.Request)
  {
    let response = Post.SelectedPostAlbum.Response()
    presenter?.presentSelectedPostAlbum(response: response)
  }
}
