//
//  PostViewController.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 31/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDisplayLogic: class
{
  func displaySomething(viewModel: Post.Something.ViewModel)
}

class PostViewController: UIViewController, PostDisplayLogic, UITableViewDataSource, UITableViewDelegate
{
  var interactor: (PostBusinessLogic & PostDataStore)?
  var router: (NSObjectProtocol & PostRoutingLogic & PostDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PostInteractor()
    let presenter = PostPresenter()
    let router = PostRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    initLayout()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  @IBOutlet weak var postTableView: UITableView!
  func initLayout()
  {
    title = "Post"
    
    postTableView.register(UINib(nibName: "PostMessageTableViewCell", bundle: nil), forCellReuseIdentifier: "PostMessageTableViewCell")
    postTableView.register(UINib(nibName: "PostPhotoTableViewCell", bundle: nil), forCellReuseIdentifier: "PostPhotoTableViewCell")
  }
  
  func doSomething()
  {
    let request = Post.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Post.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
  
  // MARK: UITableViewDataSource
  
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return (interactor?.album.photos.count)! + 1
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    if (indexPath.row == 0) {
      // message cell
      let cell = tableView.dequeueReusableCell(withIdentifier: "PostMessageTableViewCell", for: indexPath) as! PostMessageTableViewCell
      cell.titleLabel.text = interactor?.album.title
      return cell
    } else {
      // photo cell
      let item:PostPhoto = (interactor?.album.photos[indexPath.row - 1])!
      let cell = tableView.dequeueReusableCell(withIdentifier: "PostPhotoTableViewCell", for: indexPath) as! PostPhotoTableViewCell
      cell.photoImageView.sd_setImage(with: URL(string: item.url), placeholderImage: UIImage(named: "placeholder"))
      return cell
    }
  }
}
