//
//  PostPresenter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 31/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostPresentationLogic
{
  func presentSelectedPostAlbum(response: Post.SelectedPostAlbum.Response)
}

class PostPresenter: PostPresentationLogic
{
  weak var viewController: PostDisplayLogic?
  
  // MARK: Do something
  
  func presentSelectedPostAlbum(response: Post.SelectedPostAlbum.Response)
  {
    let viewModel = Post.SelectedPostAlbum.ViewModel()
    viewController?.displaySelectedPostAlbum(viewModel: viewModel)
  }
}
