//
//  NewPostPresenter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 29/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPostPresentationLogic
{
  func presentAlertDiscardNewPost(response: NewPost.AlertDiscardNewPost.Response)
  func presentDiscardNewPost(response: NewPost.DiscardNewPost.Response)
  
  func presentAlertCreateNewPost(response: NewPost.AlertCreateNewPost.Response)
  
  func presentTextViewPlaceholder(response: NewPost.TextViewPlaceholder.Response)
  
  func presentAlertAddPhoto(response: NewPost.AlertAddPhoto.Response)
  func presentPickPhoto(response: NewPost.PickPhoto.Response)
  func presentAddPhoto(response: NewPost.AddPhoto.Response)
  
  func presentAlertRemovePhoto(response: NewPost.AlertRemovePhoto.Response)
  func presentRemovePhoto(response: NewPost.RemovePhoto.Response)
}

class NewPostPresenter: NewPostPresentationLogic
{
  weak var viewController: NewPostDisplayLogic?
  
  // MARK: Do something
  
  func presentAlertDiscardNewPost(response: NewPost.AlertDiscardNewPost.Response) {
    let viewModel = NewPost.AlertDiscardNewPost.ViewModel()
    viewController?.displayAlertDiscardNewPost(viewModel: viewModel)
  }
  
  func presentDiscardNewPost(response: NewPost.DiscardNewPost.Response) {
    let viewModel = NewPost.DiscardNewPost.ViewModel()
    viewController?.displayDiscardNewPost(viewModel: viewModel)
  }
  
  func presentAlertCreateNewPost(response: NewPost.AlertCreateNewPost.Response) {
    let viewModel = NewPost.AlertCreateNewPost.ViewModel()
    viewController?.displayAlertCreateNewPost(viewModel: viewModel)
  }
  
  func presentTextViewPlaceholder(response: NewPost.TextViewPlaceholder.Response) {
    let isEmpty:Bool = response.textCount == 0
    
    let viewModel = NewPost.TextViewPlaceholder.ViewModel(isHidden: !isEmpty)
    viewController?.displayTextViewPlaceholder(viewModel: viewModel)
  }
  
  func presentAlertAddPhoto(response: NewPost.AlertAddPhoto.Response) {
    let viewModel = NewPost.AlertAddPhoto.ViewModel()
    viewController?.displayAlertAddPhoto(viewModel: viewModel)
  }
  
  func presentPickPhoto(response: NewPost.PickPhoto.Response) {
    let viewModel = NewPost.PickPhoto.ViewModel(imageSourceType: response.imageSourceType)
    viewController?.displayPickPhoto(viewModel: viewModel)
  }
  
  func presentAddPhoto(response: NewPost.AddPhoto.Response) {
    let viewModel = NewPost.AddPhoto.ViewModel()
    viewController?.displayAddPhoto(viewModel: viewModel)
  }
  
  func presentAlertRemovePhoto(response: NewPost.AlertRemovePhoto.Response)
  {
    let viewModel = NewPost.AlertRemovePhoto.ViewModel(photoIndex: response.photoIndex)
    viewController?.displayAlertRemovePhoto(viewModel: viewModel)
  }
  
  func presentRemovePhoto(response: NewPost.RemovePhoto.Response)
  {
    let viewModel = NewPost.RemovePhoto.ViewModel()
    viewController?.displayRemovePhoto(viewModel: viewModel)
  }
}
