//
//  NewPostModels.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 29/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewPost
{
  // MARK: Use cases
  
  enum AlertDiscardNewPost
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum DiscardNewPost
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum AlertCreateNewPost
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum TextViewPlaceholder
  {
    struct Request
    {
      var text: String
    }
    struct Response
    {
      var textCount: Int
    }
    struct ViewModel
    {
      var isHidden: Bool
    }
  }
  
  enum AlertAddPhoto
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum PickPhoto
  {
    struct Request
    {
      var imageSourceType: UIImagePickerController.SourceType
    }
    struct Response
    {
      var imageSourceType: UIImagePickerController.SourceType
    }
    struct ViewModel
    {
      var imageSourceType: UIImagePickerController.SourceType
    }
  }
  
  enum AddPhoto
  {
    struct Request
    {
      var selectedImage: UIImage
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum AlertRemovePhoto
  {
    struct Request
    {
      var photoIndex: Int
    }
    struct Response
    {
      var photoIndex: Int
    }
    struct ViewModel
    {
      var photoIndex: Int
    }
  }
  
  enum RemovePhoto
  {
    struct Request
    {
      var photoIndex: Int
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
