//
//  NewPostPresenter.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 29/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPostPresentationLogic
{
  func presentSomething(response: NewPost.Something.Response)
}

class NewPostPresenter: NewPostPresentationLogic
{
  weak var viewController: NewPostDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NewPost.Something.Response)
  {
    let viewModel = NewPost.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
