//
//  NewPostViewController.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 29/12/62 BE.
//  Copyright (c) 2562 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPostDisplayLogic: class
{
  func displaySomething(viewModel: NewPost.Something.ViewModel)
}

class NewPostViewController: UIViewController, NewPostDisplayLogic, UITextViewDelegate
{
  var interactor: NewPostBusinessLogic?
  var router: (NSObjectProtocol & NewPostRoutingLogic & NewPostDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = NewPostInteractor()
    let presenter = NewPostPresenter()
    let router = NewPostRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    initLayout()
    doSomething()
  }
  
  // MARK: IBOutlet
  
  @IBOutlet weak var postTextView: UITextView!
  @IBOutlet weak var placeholderLabel: UILabel!
  
  // MARK: IBAction
  
  @IBAction func onPressCloseButton(_ sender: Any) {
    self.dismiss(animated: true, completion: nil)
  }
  
  @IBAction func onPressCreateButton(_ sender: Any) {
    let alert = UIAlertController(title: "New Post", message:"Create new post completed.", preferredStyle: UIAlertController.Style.alert)
    alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: { (action: UIAlertAction!) in
      self.dismiss(animated: true, completion: nil)
    }))
    self.present(alert, animated: true, completion: nil)
  }
  
  // MARK: Do something
  
  func initLayout()
  {
    title = "New Post"
    
    postTextView.layer.borderWidth = 1
    postTextView.layer.borderColor = UIColor(red:60/255, green:60/255, blue:67/255, alpha: 0.3).cgColor
    postTextView.layer.cornerRadius = 8
    
    let tap = UITapGestureRecognizer(target: self.view, action: #selector(UIView.endEditing(_:)))
    view.addGestureRecognizer(tap)
  }
  
  func doSomething()
  {
    let request = NewPost.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: NewPost.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
  
  // MARK: UITextViewDelegate
  
  func textViewDidBeginEditing(_ textView: UITextView) {
    if textView.text.count == 0 {
      placeholderLabel.isHidden = false
    } else {
      placeholderLabel.isHidden = true
    }
  }
  
  func textViewDidEndEditing(_ textView: UITextView) {
    if textView.text.count == 0 {
      placeholderLabel.isHidden = false
    } else {
      placeholderLabel.isHidden = true
    }
  }
  
  func textViewDidChange(_ textView: UITextView) {
    if textView.text.count == 0 {
      placeholderLabel.isHidden = false
    } else {
      placeholderLabel.isHidden = true
    }
  }
}
