//
//  PostPresenterTests.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 01/01/63 BE.
//  Copyright (c) 2563 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import LinePreTest
import XCTest

class PostPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PostPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPostPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPostPresenter()
  {
    sut = PostPresenter()
  }
  
  // MARK: Test doubles
  
  class PostDisplayLogicSpy: PostDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Post.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = PostDisplayLogicSpy()
    sut.viewController = spy
    let response = Post.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
