//
//  PostPresenterTests.swift
//  LinePreTest
//
//  Created by Thanaphat Suwannikornkul on 01/01/63 BE.
//  Copyright (c) 2563 Thanaphat Suwannikornkul. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import LinePreTest
import XCTest

class PostPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PostPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPostPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPostPresenter()
  {
    sut = PostPresenter()
  }
  
  // MARK: Test doubles
  
  class PostDisplayLogicSpy: PostDisplayLogic
  {
    var displaySelectedPostAlbumCalled = false
    var displayPhotosViewerCalled = false
    
    func displaySelectedPostAlbum(viewModel: Post.SelectedPostAlbum.ViewModel) {
      displaySelectedPostAlbumCalled = true
    }
    
    func displayPhotosViewer(viewModel: Post.PhotosViewer.ViewModel) {
      displayPhotosViewerCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSelectedPostAlbum()
  {
    // Given
    let spy = PostDisplayLogicSpy()
    sut.viewController = spy
    let response = Post.SelectedPostAlbum.Response()

    // When
    sut.presentSelectedPostAlbum(response: response)

    // Then
    XCTAssertTrue(spy.displaySelectedPostAlbumCalled, "presentSelectedPostAlbum(response:) should ask the view controller to display the result")
  }
  
  func testPresentPhotosViewer()
  {
    // Given
    let spy = PostDisplayLogicSpy()
    sut.viewController = spy
    let response = Post.PhotosViewer.Response(startIndex: 0, photos: [
      PostPhoto(title: "Post Photo Title 00", url: "https://lorempixel.com/1024/768/abstract/?26180", thumbnail: "https://lorempixel.com/150/150/abstract/?60610"),
      PostPhoto(title: "Post Photo Title 01", url: "https://lorempixel.com/1024/768/abstract/?59644", thumbnail: "https://lorempixel.com/150/150/abstract/?61925")
    ])

    // When
    sut.presentPhotosViewer(response: response)

    // Then
    XCTAssertTrue(spy.displayPhotosViewerCalled, "presentPhotosViewer(response:) should ask the view controller to display the result")
  }
}
